### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Glutexo** [Glutexo/onigumo#97]
And link it from the README.

**Comment by nappex** [comment]
huuu, I was studied licenses some times ago. And now I have better overview about its.
What license do you want to use?

I have three candidate:
1) gplv3 to support fight of gnu and amazing idea of copyleft
2) bsd/MIT because I like the non restrictive approach
3) beerware license which is really punk and exotic which send message to world that no license can avoid abuse

**Comment by Glutexo** [comment]
I’d go with MIT for the sake of simplicity. It’s non-restrictive and standard.

**Comment by Glutexo** [comment]
#123
